sudo: required
language: java
jdk: openjdk8

os:
  - linux

services:
  - docker

before_install:
  # Install Nextflow
  - export NXF_VER=19.10.0 && curl -fsSL get.nextflow.io | bash
  - chmod 777 nextflow
  - wget -O test-data.tar.gz --no-check-certificate 'https://drive.google.com/file/d/1yP9kUy16jTNW94F0KzE_LrYU4MJY3Auc/view?usp=sharing'
  - tar -xzvf test-data.tar.gz 

script:
  # Run test script here
  - python3 tests/test_runner.py tests/tests.json
