sudo: required
language: java
jdk: openjdk8

os:
  - linux

services:
  - docker

before_install:
  - curl -fsSL get.nextflow.io | bash
  - chmod +x nextflow
  - wget -O test-data.tar.gz "https://drive.google.com/uc?export=download&id=1BHqUT1Bs0YMV5cKWzdeq2hjptaZM3ctx"
  - tar -xzvf test-data.tar.gz 

script:
  # Run test script here
  - python3 tests/test_runner.py tests/tests.json
 
