sudo: required
language: java
jdk: openjdk8

os:
  - linux

services:
  - docker

before_install:
  - curl -fsSL get.nextflow.io | bash
  - chmod +x nextflow
  - wget -O test-data.tar.gz  "https://drive.google.com/uc?export=download&id=1CAZ2-6ZeLXU52_Yx7kFy3JPCa_ER7kcg"
  - tar -xzvf test-data.tar.gz 

script:
  # Run test script here
  - ./nextflow run make_bam_and_qc.nf --sample tests/test_make_bam_and_qc.tsv -profile test
