sudo: required
language: java
jdk: openjdk8

os:
  - linux

services:
  - docker

before_install:
  - export NXF_VER=19.05.0-edge && curl -fsSL get.nextflow.io | bash 
  - chmod +x nextflow
  - wget -O test-data.tar.gz --no-check-certificate 'https://docs.google.com/uc?export=download&id=13kwUPGAPrQJcKj2_IKHP2p3dlCqLdcZ7'
  - tar -xzvf test-data.tar.gz 

script:
  # Run test script here
  - python3 tests/test_runner.py tests/tests.json
 
