sudo: required
language: java
jdk: openjdk8

os:
  - linux

services:
  - docker

before_install:
  - export NXF_VER=19.03.0-edge && curl -fsSL get.nextflow.io | bash 
  - chmod +x nextflow
  - wget -O test-data.tar.gz "https://drive.google.com/uc?export=download&id=130VvnMX8VaQd2i71nS4zeoLYiVLS5n06"
  - tar -xzvf test-data.tar.gz 

script:
  # Run test script here
  - python3 tests/test_runner.py tests/tests.json
 
