title: Vaporware
description: Computational Pipeline for Whole-Genome and Whole-Exome Sequencing
themeConfig:
  logo: /vaporware_stairs.jpg
  sidebar:
    - "/"
    - title: Setup
      collapsable: false
      children:
        - "/installation"
        - "/juno-setup"
        - "/aws-setup"
    - title: Usage
      collapsable: false
      children:
        - "/run-pipeline"
        - "/nextflow-basics"
        - "/working-with-containers"
    - title: Bioinformatics Components
      collapsable: false
      children:
        - "/bioinformatic-components"
        - "/intervals"
        - "/reference-resources"
        - "/gnomad"
        - "/wes-panel-of-normals"
        - "/variant-annotation-and-filtering"
    - "/aws-glossary"
    - "/troubleshooting"
    - "/contributing-to-vaporware"
  repo: mskcc/vaporware
  docsBranch: 'develop'
plugins:
- - vuepress-plugin-medium-zoom
  - selector: "#diagram"
    delay: 1000
    options:
      margin: 24
      scrollOffset: 0
