title: Vaporware
description: Computational Pipeline for Whole-Genome and Whole-Exome Sequencing
themeConfig:
  logo: /vaporware_stairs.jpg
  sidebar:
    - "/"
    - title: Setup
      collapsable: false
      children:
        - "/installation"
        - "/juno-setup"
        - "/aws-setup"
    - title: Usage
      collapsable: false
      children:
        - "/run-pipeline"
        - "/nextflow-basics"
        - "/working-with-containers"
    - title: Outputs
      collapsable: false
      children:
        - "/bam-files"
        - "/qc-outputs"
        - "/somatic-data"
        - "/germline-data"
        - "/extended-outputs"
    - title: Bioinformatics Components
      collapsable: false
      children:
        - "/read-alignment"
        - "/somatic-analyses"
        - "/germline-analyses"
    - title: Reference Resources
      collapsable: false
      children:
        - "/genome-assembly"
        - "/genomic-intervals"
        - "/repeatmasker-and-mappability-blacklist"
        - "/preferred-transcript-isoforms"
        - "/hotspot-annotation"
        - "/oncokb-annotation"
        - "/gnomad"
        - "/panel-of-normals-for-exomes"
    - title: Variant Annotation and Filtering 
      collapsable: false
      children:
        - "/somatic-snvs-and-indels"
        - "/germline-snvs-and-indels"
        - "/somatic-and-germline-svs"
    - title: Help and Other Resources 
      collapsable: false
      children:
        - "/troubleshooting"
        - "/aws-glossary"
        - "/somatic-and-germline-svs"
    - title: Contributing
      collapsable: false
      children:
        - "/contributing-to-vaporware"
  repo: mskcc/vaporware
  docsBranch: 'develop'
plugins:
- - vuepress-plugin-medium-zoom
  - selector: "#diagram"
    delay: 1000
    options:
      margin: 24
      scrollOffset: 0
