custom_logo: 'tempoLogo.png'
custom_logo_url: 'https://ccstempo.netlify.app/'
custom_logo_title: 'CCS - Tempo'

report_header_info:
    - Contact E-mail: 'skicomputing@mskcc.org'
    - Application Type: 'Exome'
    - Project Type: 'Whole Exome Repo'
    - Sequencing Platform: 'Illumina Hiseq'
    - Sequencing Setup: '2x100'
