custom_logo: 'tempoLogo.png'
custom_logo_url: 'https://ccstempo.netlify.app/'
custom_logo_title: 'CCS - Tempo'

report_header_info:
    - Contact E-mail: 'skicomputing@mskcc.org'
    - Application Type: 'Exome'
    - Project Type: 'Whole Exome Repo'
    - Sequencing Platform: 'Illumina Hiseq'
    - Sequencing Setup: '2x100'
custom_data:
    conpair:
        file_format: 'tsv'
        section_name: 'Conpair T-N Results'
        description: 'Concordance and contamination estimations for tumor–normal pairs as performed by customized version of Conpair'
        plot_type: 'table'
        pconfig:
            id: 'conpair_table'
            namespace: 'Concordance estimates'
    alfredrg:
        file_format: 'tsv'
        section_name: 'Alfred RG Aware Mapping Quality'
        description: 'Read-group aware mapping quality'
        plot_type: 'linegraph'
        pconfig:
            id: 'alfred_rgY_mapping_linegraph'
            title: 'Per read-group Mapping Quality'
            ylab: 'Read Count'
            xlab: 'MQ'
            ymin: 0 
    alfred:
        file_format: 'tsv'
        section_name: 'Alfred Mapping Quality'
        description: 'Sample mapping quality'
        plot_type: 'linegraph'
        pconfig:
            id: 'alfred_rgN_mapping_linegraph'
            title: 'Overall Sample Mapping Quality'
            ylab: 'Read Count'
            xlab: 'MQ'
            ymin: 0 
     
sp:
    conpair:
        fn: 'conpair.tsv'
    alfredrg:
        fn: '*.rgY.alfred.tsv'
    alfred:
        fn: '*.rgN.alfred.tsv'

