custom_logo: 'tempoLogo.png'
custom_logo_url: 'https://ccstempo.netlify.app/'
custom_logo_title: 'CCS - Tempo'

report_header_info:
    - Contact E-mail: 'skicomputing@mskcc.org'
    - Application Type: 'Exome'
    - Project Type: 'Whole Exome Repo'
    - Sequencing Platform: 'Illumina Hiseq'
    - Sequencing Setup: '2x100'
custom_data:
    conpair:
        file_format: 'tsv'
        section_name: 'Conpair T-N Results'
        description: 'Concordance and contamination estimations for tumor–normal pairs as performed by customized version of Conpair'
        plot_type: 'table'
        pconfig:
            id: 'conpair_table'
            namespace: 'Concordance estimates'
    alfredrg:
        file_format: 'tsv'
        section_name: 'Alfred RG Aware Mapping Quality'
        description: 'Read-group aware mapping quality'
        plot_type: 'linegraph'
        pconfig:
            id: 'alfred_rgY_mapping_linegraph'
            title: 'Per read-group Mapping Quality'
            ylab: 'Read Count'
            xlab: 'MQ'
            ymin: 0 
    alfred:
        file_format: 'tsv'
        section_name: 'Alfred Mapping Quality'
        description: 'Sample mapping quality'
        plot_type: 'linegraph'
        pconfig:
            id: 'alfred_rgN_mapping_linegraph'
            title: 'Overall Sample Mapping Quality'
            ylab: 'Read Count'
            xlab: 'MQ'
            ymin: 0 
     
sp:
    conpair:
        fn: 'conpair.tsv'
    alfredrg:
        fn: '*.rgY.MQ.alfred.tsv'
    alfred:
        fn: '*.rgN.MQ.alfred.tsv'

table_cond_formatting_rules:
    Tumor_Contamination: 
        pass:
            - lt: 1
            - eq: 1
        warn:
            - gt: 1
        fail:
            - gt: 5
    Normal_Contamination:
        pass:
            - lt: 1
            - eq: 1
        warn:
            - gt: 1
        fail:
            - gt: 5
    Concordance:
        pass:
            - gt: 90
            - eq: 90
        warn:
            - lt: 90
        fail:
            - lt: 75        
    mqc-generalstats-picard-FOLD_ENRICHMENT:
        pass:
            - gt: 45
            - eq: 45
        warn:
            - lt: 45
        fail:
            - lt: 30
    FOLD_ENRICHMENT:
        pass:
            - gt: 45
            - eq: 45
        warn:
            - lt: 45
        fail:
            - lt: 30

table_cond_formatting_colours:
    - pass: '#5cb85c'
    - warn: '#f0ad4e'
    - fail: '#d9534f'
